<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sandman.Core\Sandman.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\materials.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>materials.yaml</Link>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>